#!/usr/bin/env bash
set -euo pipefail

machine=${GCP_MACHINE:-"$(just _machine)"}

config="$(just _fast-config)"
zone="$(    echo "$config" | grep gcp_zone    | awk '{print $2}')"
project="$( echo "$config" | grep gcp_project | awk '{print $2}')"
gcp_user="$(echo "$config" | grep gcp_user    | awk '{print $2}')"

if [[ -z "$*" ]] ; then
    set -x
    gcloud beta compute ssh --zone "$zone" "$machine" --project "$project" -- sudo su -l "$gcp_user"
else
    set -x
    gcloud beta compute ssh --zone "$zone" "$machine" --project "$project" -- "$@"
fi